import {AbsoluteFill, Easing, Img, Interactive, Sequence, interpolate, staticFile, useCurrentFrame} from "remotion";

const Card: React.FC<{top:number;color:string;title:string;detail:string;delay:number}> = ({top,color,title,detail,delay}) => {
  const frame=useCurrentFrame();
  return <Interactive.Div name="Ingredient check" style={{position:"absolute",left:70,right:70,top,background:"rgba(8,18,31,.92)",border:"1px solid rgba(255,255,255,.18)",borderLeft:`8px solid ${color}`,borderRadius:24,padding:"26px 30px",opacity:interpolate(frame,[delay,delay+16],[0,1],{extrapolateLeft:"clamp",extrapolateRight:"clamp",easing:Easing.bezier(.16,1,.3,1)}),translate:`0 ${interpolate(frame,[delay,delay+16],[40,0],{extrapolateLeft:"clamp",extrapolateRight:"clamp"})}px`}}><div style={{fontSize:38,fontWeight:800}}>{title}</div><div style={{fontSize:24,color:"#aebbc9",marginTop:8,fontFamily:"monospace"}}>{detail}</div></Interactive.Div>;
};

const Title: React.FC<{kicker:string;children:React.ReactNode}> = ({kicker,children}) => {const frame=useCurrentFrame();return <><Interactive.Div name="Kicker" style={{position:"absolute",top:160,left:70,right:70,color:"#8ee3c1",fontSize:24,fontWeight:900,letterSpacing:5,opacity:interpolate(frame,[0,15],[0,1],{extrapolateRight:"clamp"})}}>{kicker}</Interactive.Div><Interactive.Div name="Title" style={{position:"absolute",top:220,left:70,right:70,color:"#f5f0e7",fontSize:88,lineHeight:1.02,fontWeight:850,letterSpacing:-5,opacity:interpolate(frame,[4,24],[0,1],{extrapolateRight:"clamp"}),translate:`0 ${interpolate(frame,[4,24],[45,0],{extrapolateRight:"clamp"})}px`}}>{children}</Interactive.Div></>};

const Backdrop=()=> <AbsoluteFill style={{backgroundColor:"#07111f"}}><Img src={staticFile("vertical-background.png")} style={{width:"100%",height:"100%",objectFit:"cover",opacity:.32}}/><div style={{position:"absolute",inset:0,background:"linear-gradient(180deg,rgba(7,17,31,.1),rgba(7,17,31,.88))"}}/></AbsoluteFill>;

const SceneOne=()=> <AbsoluteFill><Backdrop/><Title kicker="THE HIDDEN FAILURE">It looks complete.<br/><span style={{color:"#ff715b"}}>The links are empty.</span></Title><Card top={650} color="#ff715b" title="2 个 西红柿" detail="quantity: 0 · unit: ∅ · food: ∅" delay={24}/><Card top={850} color="#ff715b" title="3 个 鸡蛋" detail="the whole phrase lives in note" delay={38}/></AbsoluteFill>;
const SceneTwo=()=> <AbsoluteFill><Backdrop/><Title kicker="FUZZY MATCHES LIE">水 is not 水芹.<br/>鸡蛋 is not 鸡蛋果.</Title><Card top={700} color="#ff715b" title="Near match rejected" detail="expected name / ID must match" delay={22}/><Card top={900} color="#8ee3c1" title="Correct object selected" detail="番茄 ✓  鸡蛋 ✓" delay={36}/></AbsoluteFill>;
const SceneThree=()=> <AbsoluteFill><Backdrop/><Title kicker="BEFORE EVERY SAVE">Run the gate.<br/><span style={{color:"#8ee3c1"}}>Then read it back.</span></Title>{["5/5 structured ingredient rows","method coverage passed","category · tag · tool linked","番茄 + 鸡蛋 filters passed"].map((x,i)=><Card key={x} top={620+i*180} color="#8ee3c1" title={`✓ ${x}`} detail={i===3?"verified in a real Mealie 3.25.1 instance":"deterministic check"} delay={18+i*9}/>)}</AbsoluteFill>;
const SceneFour=()=> <AbsoluteFill><Backdrop/><Title kicker="OPEN SOURCE · MIT">Mealie Agent Toolkit</Title><Interactive.Div name="Closing copy" style={{position:"absolute",top:520,left:70,right:70,color:"#aebbc9",fontSize:42,lineHeight:1.3}}>Quality gates for agents that create recipes, plans, filters, and shopping data.</Interactive.Div><Interactive.Div name="GitHub URL" style={{position:"absolute",bottom:190,left:70,right:70,background:"#ff715b",color:"#07111f",borderRadius:24,padding:"28px 32px",fontSize:30,fontWeight:900,textAlign:"center"}}>github.com/alanthssss/mealie-agent-toolkit</Interactive.Div></AbsoluteFill>;

export const LaunchVideo:React.FC=()=> <AbsoluteFill style={{fontFamily:"Arial, Helvetica, sans-serif"}}><Sequence durationInFrames={135}><SceneOne/></Sequence><Sequence from={135} durationInFrames={135}><SceneTwo/></Sequence><Sequence from={270} durationInFrames={150}><SceneThree/></Sequence><Sequence from={420} durationInFrames={120}><SceneFour/></Sequence></AbsoluteFill>;
